import fs from 'fs';
import path from 'path';
import os from 'os';
import { spawnSync } from 'child_process';
import { fileURLToPath } from 'url';

/**
 * Cross-platform "drop a desktop shortcut for the dashboard" helper.
 *
 * Called from `aaas dashboard` on every invocation. Best-effort and
 * idempotent: if the shortcut already exists, returns without writing.
 * On unsupported / headless environments returns silently — never throws.
 *
 * Returns `{ created: boolean, path?: string, reason?: string }` so the
 * caller can print a confirmation line on the first creation only.
 */

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// AaaS icon bundled with the package. Windows shortcuts (.lnk) require an
// .ico file; Linux .desktop files accept .png. macOS skips icons entirely.
const ICON_ROOT = path.resolve(__dirname, '..', '..', 'streetai');
const ICON_ICO = path.join(ICON_ROOT, 'aaas-icon.ico');
const ICON_PNG = path.join(ICON_ROOT, 'aaas-icon.png');

const SHORTCUT_NAME = 'AaaS (Agent as a Service)';

/**
 * Remove an old-name shortcut file from a previous install. Silent on any
 * error — the new shortcut is the source of truth from here forward.
 */
function cleanupLegacy(desktop, legacyName) {
  const old = path.join(desktop, legacyName);
  try { if (fs.existsSync(old)) fs.unlinkSync(old); } catch { /* ignore */ }
}

function desktopDir() {
  const home = os.homedir();
  if (!home) return null;
  const desktop = path.join(home, 'Desktop');
  return fs.existsSync(desktop) ? desktop : null;
}

export function ensureDashboardShortcut() {
  // Escape hatches: CI, explicit opt-out, headless containers.
  if (process.env.CI || process.env.AAAS_NO_SHORTCUT) {
    return { created: false, reason: 'opted-out' };
  }
  const desktop = desktopDir();
  if (!desktop) return { created: false, reason: 'no-desktop' };

  try {
    if (process.platform === 'win32') return createWindowsShortcut(desktop);
    if (process.platform === 'darwin') return createMacShortcut(desktop);
    return createLinuxShortcut(desktop);
  } catch {
    // Never let a shortcut hiccup affect the actual command.
    return { created: false, reason: 'error' };
  }
}

// ─── Windows (.lnk via PowerShell) ───────────────────────────────────
function createWindowsShortcut(desktop) {
  const file = path.join(desktop, `${SHORTCUT_NAME}.lnk`);
  // Clean up the previous-name shortcut from earlier installs so users
  // don't end up with two icons after this rename.
  cleanupLegacy(desktop, 'AaaS Dashboard.lnk');
  if (fs.existsSync(file)) return { created: false, reason: 'exists', path: file };

  const esc = (s) => s.replace(/'/g, "''");
  const node = esc(process.execPath);
  const script = esc(process.argv[1] || '');
  const target = esc(file);
  const workDir = esc(os.homedir());
  // Windows requires a .ico (or .exe/.dll with icon resources). PNG icons
  // silently fail with "no icon" — that's what the early version hit.
  const iconLine = fs.existsSync(ICON_ICO)
    ? `$s.IconLocation='${esc(ICON_ICO)}';`
    : '';

  const ps = [
    `$s=(New-Object -ComObject WScript.Shell).CreateShortcut('${target}');`,
    `$s.TargetPath='${node}';`,
    `$s.Arguments='"${script}" dashboard';`,
    `$s.WorkingDirectory='${workDir}';`,
    `$s.Description='Open the AaaS hub dashboard';`,
    iconLine,
    `$s.Save();`,
  ].join(' ');

  const r = spawnSync('powershell', ['-NoProfile', '-Command', ps], { stdio: 'ignore' });
  if (r.status === 0 && fs.existsSync(file)) return { created: true, path: file };
  return { created: false, reason: 'powershell-failed' };
}

// ─── macOS (.command shell script) ───────────────────────────────────
// Double-clickable in Finder. Custom .icns icons require AppleScript
// gymnastics, so we skip the icon on macOS — the system uses Terminal's
// default. The shortcut still works.
function createMacShortcut(desktop) {
  const file = path.join(desktop, `${SHORTCUT_NAME}.command`);
  cleanupLegacy(desktop, 'AaaS Dashboard.command');
  if (fs.existsSync(file)) return { created: false, reason: 'exists', path: file };

  const node = process.execPath;
  const script = process.argv[1] || '';
  const body = `#!/bin/bash
# AaaS Hub Dashboard — generated by aaas
exec "${node}" "${script}" dashboard
`;
  fs.writeFileSync(file, body, 'utf-8');
  try { fs.chmodSync(file, 0o755); } catch { /* non-fatal */ }
  return { created: true, path: file };
}

// ─── Linux (.desktop entry) ──────────────────────────────────────────
function createLinuxShortcut(desktop) {
  const file = path.join(desktop, `${SHORTCUT_NAME}.desktop`);
  cleanupLegacy(desktop, 'AaaS-Dashboard.desktop');
  if (fs.existsSync(file)) return { created: false, reason: 'exists', path: file };

  const node = process.execPath;
  const script = process.argv[1] || '';
  // .desktop files accept .png natively.
  const iconLine = fs.existsSync(ICON_PNG) ? `Icon=${ICON_PNG}\n` : '';
  const entry = `[Desktop Entry]
Type=Application
Name=AaaS Dashboard
Comment=Open the AaaS hub dashboard
Exec="${node}" "${script}" dashboard
${iconLine}Terminal=true
Categories=Development;Utility;
`;
  fs.writeFileSync(file, entry, 'utf-8');
  try { fs.chmodSync(file, 0o755); } catch { /* non-fatal */ }
  return { created: true, path: file };
}
